policy:
  approval:
    - if:
        - Admins approved

approval_rules:
  - name: Admins approved
    requires:
      count: 1
      users: ["t8rafa"]
    options:
      methods:
        github_review: false
