policy:
  approval:
  - the devtools team has approved

  disapproval:
    requires:
      organization:
      - "Linux2Pro"

approval_rules:
- name: the devtools team has approved
  requires:
    count: 1
    users: ["t8rafa"]
