policy:
  approval:
    - or:
      - Admins approved
  disapproval:
    requires:
      organizations: ["Linux2Pro"]

approval_rules:
  - name: Admins approved
    requires:
      count: 2
      users: ["t8rafa", "jniltinho"]
    options:
      methods:
        github_review: false
