policy:
  approval:
  - the devtools team has approved

  disapproval:
    requires:
      organizations: ["LinuxPro"]

approval_rules:
- name: the devtools team has approved
  requires:
    count: 1
    users: ["t8rafa"]
