policy:
  approval:
    - one approval from JNILTINHO

approval_rules:
  - name: one approval from JNILTINHO
    requires:
      count: 1
      users: ["t8rafa", "mathmed"]


options:
  request_review:
    enabled: true
    mode: all-users|random-users|teams
